### ISSUE TITLE
var imul = stdlib.Math.imul produces Binary node for "." instead of Dot

### ISSUE THREAD

**Issue by lukewagner** [kripken/cashew#10]
For regularity, it would be nice if this was parsed as:
  Var('imul', Dot(Dot(Name('stdlib'), 'Math'), 'imul')
It's currently parsed as:
  Var('imul', Binary('.', Dot(Name('stdlib'), 'Math'), Name('imul'))
which requires workarounds.

**Comment by kripken** [comment]
It would be more consistent to fix it the other way I think, as we do emit `Binary('=', ..)` and `Binary(',', ..)`. Or we could emit `Dot, Assign, Comma` nodes for those three. Which do you prefer?

**Comment by lukewagner** [comment]
Binary('=') and Binary(',') make since the left and right hand sides are general ASTs.  The rhs of a Dot can only be a Name/IString which is kindof nice b/c it removes any question of how a.b.c nests ((a.b).c or a.(b.c), though I guess this is obvious).  OTOH, if it simpler to use Binary everywhere, we could do that too.

**Comment by kripken** [comment]
Ah, good point. I'll do it as you suggested, then.

**Comment by kripken** [comment]
Done. Note though that you need to implement two versions of `makeDot` now, where it receives an IString, and where it receives an AST node. Maybe that changes your mind on what is cleaner here? I'm ok either way.

**Comment by lukewagner** [comment]
Oh, is the issue that we recurse on the rhs, get a Name node (not IString) and then, when we see we have a dot, we have no way to unpack the name node into the IString?  In theory, you could have a IString Builder::unpackName(NodeRef), but I can just as well do this inside my Builder::makeDot.  Either way, the Dot still seems nice.

**Comment by kripken** [comment]
Yes, that's the issue.

Ok, sounds like we can leave this as-is and close this.
