### ISSUE TITLE
do{}while() parsed as expression statement

### ISSUE THREAD

**Issue by lukewagner** [kripken/cashew#12]
The result of parsing 'function() { do{}while(1); }' seems to be makeStatement(makeDo()) when I would just expect a makeDo().

**Comment by kripken** [comment]
We take semicolons to mean "statement", just like `x=y` is an expression and `x=y;` is a statement. For `do` the distinction does seem odd as there isn't an expression form, so I guess we could remove that. However if we did, then the transformation would no longer be perfectly reversible, the semicolon would be eaten.

**Comment by lukewagner** [comment]
Ah, so the central issue is the semicolon at the end of do{}while.  Do you happen to know if, according to ES6, is the semicolon part of the do{}while or is it actually an empty-statement that follows the do{}while?

**Comment by kripken** [comment]
Hmm, I do not. But uglify treats it as the former, fwiw.
